Add Group Vibe Frontend
aroomvithavue/QuickChat pull request #42
Opened 2022-12-01 22:52 UTC by farooqashar

This handles issue #16 

This PR does the following: 
- Sets up the two emojis for confused and happy on the sidebar of main messaging view that scale in size depending on counts
- Sets up socket events for sending over confused and happy votes
- Initially gets the group vibe counts when one joins a room
- Updates the local group vibe counts when there is a vote received by a user

There is a placeholder for some backend functions when it is implemented.

2022-12-02 16:31 UTC, Lavrans requested changes
I've made one comment on the front-end code. Otherwise I think we should wait until #45  is merged and implement socket backend to utilize real collections.

2022-12-02 16:31 UTC, Lavrans commented on frontend/src/views/MainChatView.vue
> +                src="https://img.icons8.com/ios-glyphs/50/null/question--v1.png"
I think we should do this using some basic math and CSS properties

2022-12-02 16:31 UTC, Lavrans commented on backend/api/index.ts
> +      data.reaction,
I think we should wait till backend collections are ready and implement this properly before we merge with main.

2022-12-04 21:52 UTC, jmgcov approved these changes
Lgtm

2022-12-04 22:04 UTC, jmgcov approved these changes
Ok!

2022-12-04 22:04 UTC, merged